### ISSUE TITLE
Implement Autoplay Option

### ISSUE THREAD

**Issue by sprankhub** [peduarte/wallop#13]
Implement an autoplay option (e.g. called `autoPlay`), which is a boolean that says whether the slider should slide automatically. There should also be another option (e.g. called `interval`), which is an integer that says after how many ms the slide should change when autoplay is enabled. That would be really cool :-)

Thanks for your work!

**Comment by rchrd2** [comment]
Here's an improvement on the above code. It resets the autoplay timer when user clicks next.
```
  (function(){
    var wallopEl = document.querySelector('.Wallop');
    var slider = new Wallop(wallopEl);
    var autoPlayMs = 3000;
    var nextTimeout;
    var loadNext = function() {
      var nextIndex = (slider.currentItemIndex + 1) % slider.allItemsArray.length;
      slider.goTo(nextIndex);
    }
    nextTimeout = setTimeout(function() { loadNext(); }, autoPlayMs);
    slider.on('change', function() {
      clearTimeout(nextTimeout);
      nextTimeout = setTimeout(function() { loadNext(); }, autoPlayMs);
    });
  })();
```

**Comment by S1SYPHOS** [comment]
Working great, thx for the code @rchrd2, but is there an easy way to implement pause-on-hover functionality?

**Comment by honzabilek4** [comment]
Simply add a new listener on `mouseenter` with `clearTimeout(nextTimeout)` and set it again on `mouseleave` :)

**Comment by S1SYPHOS** [comment]
Thanks again!

**Comment by garethjohnsdesign** [comment]
Can you give an example of this code? @honzabilek4

**Comment by S1SYPHOS** [comment]
@garethjohnsdesign: Something like this:
```js
    wallopEl.addEventListener('mouseenter', function() {
      clearTimeout(nextTimeout);
    });
    wallopEl.addEventListener('mouseleave', function() {
      nextTimeout = setTimeout(function() {
        loadNext();
      }, autoPlayMs);
```
