### ISSUE TITLE
CustomEvents Polyfill breaks Android 4.0-4.3

### ISSUE THREAD

**Issue by felics** [peduarte/wallop#28]
Solution: Use [this polyfill](https://github.com/jonathantneal/EventListener
) instead

**Comment by peduarte** [comment]
Thanks!

**Comment by peduarte** [comment]
Hey, I've released a v2 of the slider, is this still breaking?

**Comment by crisbeto** [comment]
It still is @peduarte. I just got the same error in Safari 5.1.7

**Comment by peduarte** [comment]
@crisbeto Nice one man!
