### ISSUE TITLE
Using goTo to the current slide causes slide to disappear after the transition effect

### ISSUE THREAD

**Issue by bryanwaddington** [peduarte/wallop#37]
If you set up custom pagination buttons, have a transition effect enabled and click the same custom pagination button more once then the transition effect occurs (it shouldn't) and the slide disappears. See the following example

http://codepen.io/bryanwadd/pen/wKBWwo

This seems to occur because the goTo() function assumes that you are going to a slide that is either above or below the current index and always adds appropriate classes. Adding a simple check to only change the classes if the index number supplied to goTo() is different from the current slide index fixes the problem.

**Comment by peduarte** [comment]
Ohhhhhhh, this is genius. Thank you, man. 
Will look at your PR.

**Comment by bryanwaddington** [comment]
Glad to help. I have made your suggested change.

Thanks the script btw, very useful.

**Comment by peduarte** [comment]
Done!
