### ISSUE TITLE
Scale method needs some extra styling

### ISSUE THREAD

**Issue by MissFerrety** [peduarte/wallop#39]
I'm just checking out the examples with the default styles ([animations.html in v2.1.4](https://github.com/peduarte/wallop/blob/v2.1.4/examples/animations.html)) and noticed that the Scale method leaves behind some invisible boxes that obscure the controls.  I only played with it very briefly (AKA it can probably be done in a cleaner fashion), but I fixed the issue by containing the slides inside an additional div and implementing some `overflow:hidden;` and `z-index` styles.

**Comment by peduarte** [comment]
Hey there!

Interesting, I think that might be outdated.
Do you get the same issue here: http://codepen.io/peduarte/pen/jbNRZP

**Comment by MissFerrety** [comment]
Works fine in the CodePen.

I just downloaded the 2.1.4 zip this morning.

**Comment by peduarte** [comment]
Then I must've forgotten to update the example.
Will take a look at this tonight.

Thanks 🙌

**Comment by peduarte** [comment]
Fixed! :) Thanks!
