### ISSUE TITLE
Fade method z-index causes slide content to be inaccessible

### ISSUE THREAD

**Issue by MissFerrety** [peduarte/wallop#40]
Due to use of a higher `z-index` for a slide with `opacity: 0`, the user can only interact with invisible content on the previous slide.

**Comment by peduarte** [comment]
Where are you seeing this? Codepen, or examples in this repo?

Thanks!

**Comment by MissFerrety** [comment]
Using default settings from 4.1.2, I am marking up divs that have text and buttons in them.  I noticed the issue because the button's hover state was not triggering.

[Forked original "Fade" animation Pen](http://codepen.io/MissFerrety/pen/JYoZLZ)

On initialization, the button acts as expected.  As soon as you move away from the first slide, the cursor change is still triggered.  Once you get back to the slide with the button on it, the hover change is not triggered because the `z-index` does not recognize that slide as the current item.

**Comment by peduarte** [comment]
Fixed this :) Latest release. 2.1.6
