### ISSUE TITLE
Store "direction"

### ISSUE THREAD

**Issue by peduarte** [peduarte/wallop#43]
In order to have proper circular animations (sliding carousel) we need to know if the user is navigating `forwards` or `backwards`.

A `direction` variable must be implemented to store the direction value.
This will ensure the correct classes are added to the `next` or `previous` items based on the direction of the user.

If anyone is willing to take this up and need more info, let me know. Otherwise, I'll crack on with this as soon as I do. 

Will assign it to myself if i start progress.

✌️

**Comment by jackmu95** [comment]
I have created a pull request (https://github.com/peduarte/wallop/pull/47) which fixes the direction detection. Ans some other small issues ;)

**Comment by peduarte** [comment]
🍻

**Comment by jackmu95** [comment]
This can be closed (https://github.com/peduarte/wallop/pull/47) ;)

**Comment by peduarte** [comment]
Merged #47 
Thanks a lot @jackmu95 👊

**Comment by ladislavpr** [comment]
It seems like this issue was solved only for sliders with more than 2 items - or is this expected behaviour?

http://codepen.io/ladislav/pen/ZOrRRp

I have solved it in my project by changing isForward calculation

**Comment by ugrupp** [comment]
i agree, this behaviour with 2 slides doesn't feel 'correct'. could you provide a PR with how you fixed it for your project @ladislavpr?
