### ISSUE TITLE
Slider not displayed on Android

### ISSUE THREAD

**Issue by benkhouya** [peduarte/wallop#45]
The slider is not displayed on Android mobile ! tested with Chrome and the native browser (Android 5.1.1)

**Comment by peduarte** [comment]
Weird... 
Did you test one of the Codepen examples or you tested your own thing?

If it was your own, would you care to share your implementation and maybe I can help out.

**Comment by benkhouya** [comment]
Sorry it works fine ! Effectively the error is mine.
PS : Thanks for this useful and powerful slider.

**Comment by peduarte** [comment]
No worries. Thanks! :smile:
