### ISSUE TITLE
Fade animation does not work in Safari

### ISSUE THREAD

**Issue by MissFerrety** [peduarte/wallop#52]
What the title says :)

`animation` simply needs a duplicate `-webkit-` line.  May have this problem in other CSS as well.

**Comment by peduarte** [comment]
Wuuuuuuut, thought I had fixed this! 😐🔫

Thanks!

**Comment by peduarte** [comment]
Hi @MissFerrety I just checked the latest https://github.com/peduarte/wallop/blob/master/css/wallop--fade.css#L13-L16 and it has all the correct browser prefixes.

Going to close this, but feel free to re-open if I am missing something. 

Thanks!

**Comment by MissFerrety** [comment]
You got around to replying before I did... I was in kind of a rush and hadn't checked for an update.  :open_mouth: :athletic_shoe:
