### ISSUE TITLE
Previous slides block the current slides when you use wallop--fade.css

### ISSUE THREAD

**Issue by Gilberto06** [peduarte/wallop#54]
Hello, I love this library but I think improving this tiny detail could make it even better.

If the current slide have buttons or a div with scroll they won't work unless you send the previous slides back (z-index: 0) at the end of the animation.

You'll probably find a better solution but changing this in the wallop--fade.css fixed the issue for me:

/*
.Wallop--fade .Wallop-item--hidePrevious,
.Wallop--fade .Wallop-item--hideNext { z-index: 2; }*/
.Wallop--fade .Wallop-item--showPrevious,
.Wallop--fade .Wallop-item--showNext { z-index: 1; }

 /*==========  FADE ANIMATIONS  ==========*/
@-webkit-keyframes fadeOut {
  0% {
	opacity: 1;
	z-index: 2;
  }
  99% {
    opacity: 0;
    z-index: 2;
  }
  100% {
     opacity: 0;
     z-index: 0;
  }
}
@-moz-keyframes fadeOut {
  0% {
	opacity: 1;
	z-index: 2;
  }
  99% {
        opacity: 0;
	z-index: 2;
  }
  100% {
	 opacity: 0;
         z-index: 0;
  }
}
@-ms-keyframes fadeOut {
  0% {
	opacity: 1;
	z-index: 2;
  }
  99% {
        opacity: 0;
	z-index: 2;
  }
  100% {
     opacity: 0;
     z-index: 0;
  }
}
@keyframes fadeOut {
  0% {
	opacity: 1;
	z-index: 2;
  }
  99% {
    opacity: 0;
	z-index: 2;
  }
  100% {
	 opacity: 0;
     z-index: 0;
  }
}

**Comment by peduarte** [comment]
Thanks for this. Will take a better look when I get home. 
Quick question, which version of wallop at you using?

**Comment by Gilberto06** [comment]
wallop-2.2.2

On Mon, Oct 12, 2015 at 11:58 PM, Pedro Duarte <notifications@github.com>
wrote:

> Thanks for this. Will take a better look when I get home.
> Quick question, which version of wallop at you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peduarte/wallop/issues/54#issuecomment-147532559>.
>



-- 
Gilbert

**Comment by peduarte** [comment]
Thanks, I'll take a look. 👍

**Comment by henriquea** [comment]
Po mano arruma ai

**Comment by peduarte** [comment]
This should be fixed now. Please download latest release. 
https://github.com/peduarte/wallop/releases/tag/v2.2.3

Thanks!
