### ISSUE TITLE
Can't use removeEventListener

### ISSUE THREAD

**Issue by jamesfzhang** [peduarte/wallop#59]
In `componentWillMount`, I add an event listener to Wallop.

```js
this.wallop = new Wallop(document.querySelector('.Wallop'));
this.wallop.on('change', this.handleWallopChange);
```

In `componentWillUnmount`, I want to remove the listener

```js
this.wallop.$selector.removeEventListener('change', this.handleWallopChange);
```

This doesn't work since Wallop's implementation of [`on` uses an anonymous function](https://github.com/peduarte/wallop/blob/master/js/Wallop.js#L157). Is it possible to use the `callback` event instead and perhaps add an `off` method? Thanks.

**Comment by peduarte** [comment]
Thanks! On it.

**Comment by peduarte** [comment]
Fixed
