### ISSUE TITLE
Doesn't work for form elements

### ISSUE THREAD

**Issue by oskarrough** [peduarte/wallop#64]
Hi, as `<form>` elements have a length they can't be used as Wallop containers because of this:

```js
if (selector.length > 0) {  
  throw new Error('Selector cannot be an array, Refer to Usage documentation: https://github.com/peduarte/wallop#javascript');
} else {
  this.$selector = selector;
}
```

Any thoughts how we could like to deal with it? Something like `if (selector.tagName !== 'FORM' && selector.length > 0) {  ` perhaps?

Great module by the way, works really well otherwise!

**Comment by henriquea** [comment]
@oskarrough I know isn't the ideal solution but you could wrap your form element around a `div`.
