### ISSUE TITLE
Collaboration 

### ISSUE THREAD

**Issue by afmarchetti** [peduarte/wallop#65]
Hi Peduarte, you are a genius! Wallop is awesome.
I'm Andrea a Developer from Italy :-)

Can i use Wallop in my new front-end framework? 
take a look: https://github.com/afmarchetti/alux

Thank you!
Andrea.

**Comment by peduarte** [comment]
@afmarchetti hey, thanks! :smile: Yes you can use it, as long as it's still called Wallop and has credit to this repo.
Thanks and good luck! :)
Let me know when it's done
