### ISSUE TITLE
Autostart reset timer

### ISSUE THREAD

**Issue by afmarchetti** [peduarte/wallop#67]
Is possible reset the timer of the slide when a user click on next prev?

this is the code that i mean http://codepen.io/afmarchetti/pen/oxVeGY

**Comment by peduarte** [comment]
Yeah but that's custom JS, that's up to you to decide how you want to do it. 
What I mean is that this is not responsibility of Wallop.

Here's a tip: You'll most likely want to rely on wallops custom event: https://github.com/peduarte/wallop#listening-to-a-slide-change
