### ISSUE TITLE
Expose method for updating global variables

### ISSUE THREAD

**Issue by honzabilek4** [peduarte/wallop#69]
Hi,
I've been using wallop at some websites and I was missing a method which would update wallop's global variables and allow me to dynamically change content.

**Comment by peduarte** [comment]
Hi, I'm not sure what you mean? 
Could you give me an example why you'd need access to wallop's global variables?

Thanks

**Comment by honzabilek4** [comment]
Let's say I'd like to add/remove some slides after wallop has been initialized. Real life example would be a gallery with multiple categories, for instance. But this might come handy in general I think. Another approach would be to destroy and initialize wallop again, however this is just a few lines and it enables you to easily update wallop's inner state. What do you think?

**Comment by peduarte** [comment]
Ok let me think about this! Feel free to submit a PR with your proposal too 💛

**Comment by honzabilek4** [comment]
This has been solved and mereged in #70, so I'm closing this issue.
