### ISSUE TITLE
How to import it in an angular 2 project?

### ISSUE THREAD

**Issue by praveenpuglia** [peduarte/wallop#71]
I tried this 

```js
import Wallop from 'Wallop';
```

Says it can't find that module. Any help?

**Comment by honzabilek4** [comment]
Could you be more specific? This question is too broad, how can we know which tools/loaders are you using? :smile:

**Comment by praveenpuglia** [comment]
I didn't realize it was important to say which loaders. Now i get it.

I am using Webpack and basically using this starter pack.
https://github.com/AngularClass/angular2-webpack-starter

I am guessing that I would ideally import it in **vendor** file but not sure how.

**Comment by praveenpuglia** [comment]
I solved it by doing 

```js
import 'wallop';
```

and then in my component files I did

```js
import * as Wallop from 'wallop';
```

It works now :)
