### ISSUE TITLE
How about multiple columns?

### ISSUE THREAD

**Issue by hayatbiralem** [peduarte/wallop#72]
Current version has one column. Sometimes we need two or more columns in carousel and even  we need different column count when responsive.

Do you plan to add multiple columns feature?

**Comment by honzabilek4** [comment]
Hi,
I've been working working wallop recently and I believe that it's biggest advantage over tons of other solutions is that it's so simple, lightweight and easily customizable. In most cases, this is as much as you need. I think @peduarte was talking about extending wallop with some modules which would be totally optional allowing you to pick only the parts you really use.

**Comment by hayatbiralem** [comment]
Hi,
I think you are right. Thanks ;)

**Comment by peduarte** [comment]
Hey guys, I'd really like to keep wallop under 4kb. Like @honzabilek4 said the whole point of this library is to be simple but extensible via the API and Custom Events.

I still think the "plugins" idea would be good, but I've been too busy recently :(

**Comment by hayatbiralem** [comment]
When I met with Bootstrap Carousel, I discovered CSS classes can be very useful for this things. Than I found Wallop and I said "Wow!" because it is tiny but more effective.

I think we need more works/idea like Wallop.

Glad to hear you are busy. Keep going to learn more and more. When you're ready, we'll be here for your improvements :)

Thanks.

**Comment by peduarte** [comment]
Thanks so much @hayatbiralem 👍
