### ISSUE TITLE
New modifiers: show & hide

### ISSUE THREAD

**Issue by hayatbiralem** [peduarte/wallop#73]
Hey, I liked it very much. Thanks for this beautiful library :)

I have another suggestion.

Previous and Next modifiers are important for directional animations, I know that but some animations don't need them.

Currently we use this:

```
 .Wallop--fade .Wallop-item--hidePrevious,
 .Wallop--fade .Wallop-item--hideNext {
  visibility: visible;
  animation: fadeOut 450ms cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

.Wallop--fade .Wallop-item--showPrevious,
.Wallop--fade .Wallop-item--showNext { z-index: 1; }
```

but this would be cleaner:

```
 .Wallop--fade .Wallop-item--hide {
  visibility: visible;
  animation: fadeOut 450ms cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

.Wallop--fade .Wallop-item--show { z-index: 1; }
```

I think showClass and hideClass options would be great.

What do you think about this?

**Comment by peduarte** [comment]
If I understood your question correctly, you can already do this by passing custom options to wallop. https://github.com/peduarte/wallop#options

**Comment by hayatbiralem** [comment]
I could not think how to do that? 😅
