### ISSUE TITLE
Include main in bower.json too

### ISSUE THREAD

**Issue by nygdjs** [peduarte/wallop#77]
First of all, many thanks for Wallop, I use it for tons of  various tasks recently 🙏 

On one of these projects we handle dependencies with bower, and I have a gulp task that pick the main files based on the `bower.json`s and moves them during the build process. For Wallop this is currently not happening, because there is no `"main":` specified. 

Can you add this please?

**Comment by peduarte** [comment]
Hey sorry for the delay! I'm happy to accept a PR for this ;)
