### ISSUE TITLE
Problem with absolute positioned items, flexbox and Firefox

### ISSUE THREAD

**Issue by alexpi** [peduarte/wallop#84]
Hello,

I have a slideshow with image backgrounds and titles, centered on top of the images. I used flexbox on the slide divs, to center the absolute positioned titles on the images. This works fine in all browsers except Firefox, where the centering doesn't work as expected. I am getting jumpy title motion, or no centering at all.

I made a simple example here: [https://codepen.io/alexpi/pen/LjgBJy?editors=1100]()

I am not sure if this is Wallop's problem, a Firefox bug or my use of CSS.

**Comment by honzabilek4** [comment]
Hi, 
this obviously isn't a Wallop issue. (How could it even possibly be?)
Tip for you: try to add `flex: 1 0 auto;` to` .Wallop-item{ }` . 😉 
Regards,
JB

**Comment by honzabilek4** [comment]
Hi,
This isn't obviously a wallop bug.
Flexbox is mostly not playing very nicely with absolutely positioned elements.
You have at least two options to fix this:
- Add the images as a background and get rid of the position absolute on h1
- Use different vertical centering technique such as [this one](https://gist.github.com/honzabilek4/c9c44b2055868b1500aa781bf497fa66)
Regards,
JB

**Comment by alexpi** [comment]
Thanks,

There is a simple solution I should have thought from the beginning: Put the flexbox container and positioned elements inside a separate 'slide' div, a child of the Wallop-item. Everything works perfect now.

**Comment by honzabilek4** [comment]
Nice, please close the issue if solved. 🙂
